# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-04 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issa', '0002_auto_20201104_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_Id',
        ),
    ]
