# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-04 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issa', '0003_remove_profile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_Id',
            field=models.IntegerField(default=0),
        ),
    ]
